version: 2.1
jobs:
        build:
                machine:
                        image: android:202102-01
                steps:
                        - run: sudo apt update
                        - run: sudo apt install cpu-checker
                        - run: cat /proc/cmdline
                        - run: kvm-ok
